### ISSUE TITLE
I've made some changes. I leave them here in case you see something you like.

### ISSUE THREAD

**Issue by ajr-dev** [strboul/dotfiles#5]
I've customized your [dotfiles to work for me](https://github.com/ajr-dev/strboul_dotfiles/tree/ajr-dev).

Here are some suggestions:

 * There is a bug with the installation of autosuggestions and highlighting, which I haven't fixed yet:
```
[oh-my-zsh] plugin 'zsh-autosuggestions' not found
[oh-my-zsh] plugin 'zsh-syntax-highlighting' not found
```

 * Vim lags when I try to move through a file using j k h l.

 * Buffer mappings:
```
  " list buffers
  nmap <Leader>bb :ls<cr>

  " move through buffers
  nmap <leader>h :bp<cr>
  nmap <leader>l :bn<cr>
  
  " delete buffer
  nmap <leader>d :bd<cr>
```

```
" assign search to <Space> and backward search to Ctrl-<Space>
  map <space> /
  map <c-space> ?
```

* `set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮`.
* Remove tpm dependencie: speeds the installation process. No need to press Ctrl + I. And there is no need to update the plugins as they aren't updated often. Usually they have a couple commits a year.
* Use tmux pain-control plugin.
* You may also want to look at tmux-yank, for copy-paste support in macos and WSL. tmux-resurrect and continuum to persist tmux environment between restarts.
* Remove ~/dotfiles location requirement, by adding some variables to tmux.conf and zshrc like:
```
export DOTFILES="$(dirname "$(dirname "$(readlink "${(%):-%N}")")")"
```
* You should delete the TODOs and FIXMEs from the code and create issues instead. It's more elegant and you can use 'Fixes issue' on your commits to mark them as solved.
* You should use a function to add lines to the PATH. If I didn't have go installed I wouldn't need it in the path:
```
function pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="${PATH:+"$PATH:"}$1"
    fi
}
```
 * In `utils__yesno_prompt()` it seems as if the default option is 'no' because it is capitalized but that's not the case.

**Comment by strboul** [comment]
Interesting takes! Thanks, I'll look them

**Comment by strboul** [comment]
Thanks again for your message. I tried to respond them from my perspective:

> Vim lags when I try to move through a file using j k h l.

I don't experience such a thing.

> Buffer mappings:

I don't care about mappings so much. I often use the Vim command mode and I like it.

> Remove tpm dependencie: speeds the installation process. 

The installation speed isn't important to me. Removing tpm may matter only if it makes tmux
*significantly* faster in runtime. I like tpm as much as I like oh-my-zsh because I don't like manually managing the plugins. I used to manage the zsh plugins that way via git submodules, and I'm happy that I don't do it any more.

> tmux-resurrect and continuum to persist tmux environment between restarts.

I don't generally care about saving environments between restarts. For a few projects, I use
[tmuxp](https://github.com/tmux-python/tmuxp) and I keep the tmuxp config files inside the project folders for now.

> Remove ~/dotfiles location requirement, by adding some variables to tmux.conf and zshrc like:
> `export DOTFILES="$(dirname "$(dirname "$(readlink "${(%):-%N}")")")"`

It's a nice idea to get the dotfiles path dynamically. However, I don't think this implementation works recursively e.g. if I change the path to somewhere else. An alternative to this might be getting the git repo path from `git rev-parse --show-toplevel 2>/dev/null` but I'm afraid that can slow things. In essence, I am fine with having a home directory requirement for now.

> You should use a function to add lines to the PATH. If I didn't have go installed I wouldn't need it in the path:

I agree! It's a nice solution.
